/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.TareaControlador;
import javax.swing.table.DefaultTableModel;
import modelo.Tarea;
import modelo.TareaCount;
import java.util.List;
import javax.swing.JOptionPane;
import excepciones.TareaException;
/**
 *
 * @author nikom
 */
public class TareasVista extends javax.swing.JFrame {

    /**
     * Creates new form TareasVista
     */
    
    private TareaControlador tareaControlador;
    
    public TareasVista() {
        initComponents();
        tareaControlador = new TareaControlador();        
        cargarTareasEnTabla();
        cargarTareasEnTablaCount();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlIngresoDatos = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        lblDescripcion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaDescripcion = new javax.swing.JTextArea();
        btnGuardar = new javax.swing.JButton();
        btnBuscarTarea = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblTareasCount = new javax.swing.JTable();
        lblNombre = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        btnCambiarEstadoTarea = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTareas = new javax.swing.JTable();
        btnCargarTareas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestor de Tareas Nicolás");
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));

        pnlIngresoDatos.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingrese datos de su tarea"));

        txtNombre.setToolTipText("Ingrese nombre de la tarea");

        lblDescripcion.setText("Descripcion");

        txaDescripcion.setColumns(20);
        txaDescripcion.setLineWrap(true);
        txaDescripcion.setRows(5);
        jScrollPane1.setViewportView(txaDescripcion);

        btnGuardar.setText("Guardar Tarea");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnBuscarTarea.setText("Buscar Tarea");
        btnBuscarTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarTareaActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar Tarea");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Contador Tareas"));

        tblTareasCount.setModel(new javax.swing.table.DefaultTableModel(
            new Object[][]{},
            new String[]{"N°", "Pendientes", "Terminadas"} // Definir las columnas aquí
        ) {
            boolean[] canEdit = new boolean[]{false, false, false}; // Configurar si las columnas son editables

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblTareasCount);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
        );

        lblNombre.setText("Nombre");

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnCambiarEstadoTarea.setText("Cambiar Estado");
        btnCambiarEstadoTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarEstadoTareaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlIngresoDatosLayout = new javax.swing.GroupLayout(pnlIngresoDatos);
        pnlIngresoDatos.setLayout(pnlIngresoDatosLayout);
        pnlIngresoDatosLayout.setHorizontalGroup(
            pnlIngresoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIngresoDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlIngresoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(pnlIngresoDatosLayout.createSequentialGroup()
                        .addGroup(pnlIngresoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtId)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBuscarTarea, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCambiarEstadoTarea, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))
                        .addGroup(pnlIngresoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlIngresoDatosLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 130, Short.MAX_VALUE))
                            .addGroup(pnlIngresoDatosLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(pnlIngresoDatosLayout.createSequentialGroup()
                        .addGroup(pnlIngresoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDescripcion)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlIngresoDatosLayout.setVerticalGroup(
            pnlIngresoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIngresoDatosLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(lblDescripcion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(pnlIngresoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlIngresoDatosLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(pnlIngresoDatosLayout.createSequentialGroup()
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarTarea)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCambiarEstadoTarea)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(pnlIngresoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Tarea"));

        tblTareas.setModel(new javax.swing.table.DefaultTableModel(
            new Object[][]{},
            new String[]{"ID", "Nombre", "Descripción", "Estado"} // Definir las columnas aquí
        ) {
            boolean[] canEdit = new boolean[]{false, false, false, false}; // Configurar si las columnas son editables

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblTareas);

        btnCargarTareas.setText("Ver Tareas");
        btnCargarTareas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarTareasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(btnCargarTareas))
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(btnCargarTareas)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(pnlIngresoDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlIngresoDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String nombre = txtNombre.getText();
        String descripcion = txaDescripcion.getText();
        
        try{
            if(txtId.getText().trim().isEmpty()){
                tareaControlador = new TareaControlador();
                tareaControlador.crearTarea(nombre, descripcion);
                JOptionPane.showMessageDialog(null,
                                    "Tarea guardada satisfactoriamente",
                                    "Datos Guardados",
                                    JOptionPane.OK_OPTION);
                limpiar();
                limpiar2();
                cargarTareasEnTabla();
                cargarTareasEnTablaCount();
            }else{
                //Actualizar la tarea existente
                int id = Integer.parseInt(txtId.getText().trim());
                tareaControlador = new TareaControlador();
                tareaControlador.actualizarTarea(id, nombre, descripcion, true);
                JOptionPane.showMessageDialog(null, 
                                "Tarea editada satisfactoriamente", 
                                "Datos Editados", 
                                JOptionPane.OK_OPTION);
                limpiar();
                limpiar2();
                cargarTareasEnTabla();
                cargarTareasEnTablaCount();
            }
        
        }catch(NumberFormatException ex){
           JOptionPane.showMessageDialog(null,
                                        "El ID debe ser un número válido.", 
                                        "Error", 
                                        JOptionPane.ERROR_MESSAGE); 
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null,
                                            "Error en: " + ex.getMessage(), 
                                            "Error", 
                                            JOptionPane.ERROR_MESSAGE);
        }                                                       
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnBuscarTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarTareaActionPerformed
        try{
            int id = Integer.parseInt(txtId.getText());
            
            //Llamamos al controlador para buscar si la tarea existe o no
            Tarea tarea = tareaControlador.buscarTareaPorId(id);
        
            //Vamos a preguntar si esta la tarea
            if(tarea != null){
                txtNombre.setText(tarea.getNombre());
                txaDescripcion.setText(tarea.getDescripcion());
            }else{
                JOptionPane.showMessageDialog(
                        this,
                        "No hay tareas por ese ID, intentelo nuevamente",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
            }
            
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(
                    null,
                    "Error, solo permite numeros",
                    "Error",JOptionPane.ERROR_MESSAGE);
            limpiar();
            limpiar2();
        }
    }//GEN-LAST:event_btnBuscarTareaActionPerformed

    private void btnCargarTareasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarTareasActionPerformed
        cargarTareasEnTabla();
    }//GEN-LAST:event_btnCargarTareasActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        
        try{
                        
            int id = Integer.parseInt(txtId.getText());
            tareaControlador = new TareaControlador();
            tareaControlador.eliminarTarea(id);
            
            JOptionPane.showMessageDialog(
                        this,
                        "Tarea eliminada satisfactoriamente",
                        "Ok",
                        JOptionPane.OK_OPTION);
            cargarTareasEnTabla();
            cargarTareasEnTablaCount();
            limpiar();
            limpiar2();
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(null,"Por favor ingrese un numero válido","Error",JOptionPane.OK_OPTION);
            limpiar2();
        }catch(TareaException e){
            JOptionPane.showMessageDialog(null,e.getMessage(),"Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiar();
        limpiar2();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnCambiarEstadoTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarEstadoTareaActionPerformed
        
        Boolean estado = false;
        
        try{
            int id = Integer.parseInt(txtId.getText());
            
            //Llamamos al controlador para buscar si la tarea existe o no
            Tarea tarea = tareaControlador.buscarTareaPorId(id);
        
            //Vamos a preguntar si esta la tarea
            if(tarea != null){
                estado = tareaControlador.buscarEstadoTareaPorId(id);
                tareaControlador.cambiarEstadoTarea(id,estado);
                JOptionPane.showMessageDialog(
                        this,
                        "Estado cambiado satisactoriamente",
                        "Estado cambiado",
                        JOptionPane.OK_OPTION);
                cargarTareasEnTabla();
                cargarTareasEnTablaCount();
            }else{
                JOptionPane.showMessageDialog(
                        this,
                        "No hay tareas por ese ID, intentelo nuevamente",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
            }
            
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(
                    null,
                    "Error, solo permite numeros",
                    "Error",JOptionPane.ERROR_MESSAGE);
            limpiar();
            limpiar2();
        }
    }//GEN-LAST:event_btnCambiarEstadoTareaActionPerformed

    private void limpiar(){
        txtNombre.setText("");
        txaDescripcion.setText("");
    }
    
    private void limpiar2(){
        txtId.setText("");
    }
    
    private void cargarTareasEnTabla(){
        try{
        
            //Primero obtenemos la lista de las tareas desde el controlador
            List<Tarea> tareas = tareaControlador.listarTareas();
            
            //Obtenemos el modelo de la tabla
            DefaultTableModel modelo = (DefaultTableModel) tblTareas.getModel();
            
            //Limpiar el modelo
            modelo.setRowCount(0);
            
            //Vamos a agregar las filas con los datos de las tareas
            for(Tarea tarea : tareas){
                Object[] fila = {
                    tarea.getId(),
                    tarea.getNombre(),
                    tarea.getDescripcion(),
                    tarea.getEstado() ? "Activa" : "Inactiva"
                };
                modelo.addRow(fila);
            }
            
        }catch(Exception ex){
            System.out.println("Error al cargas tareas" + ex.getMessage());
            ex.printStackTrace();
        }
    }
    
    private void cargarTareasEnTablaCount(){
        try{
        
            //Primero obtenemos la lista de las tareas desde el controlador
            List<TareaCount> tareasCount = tareaControlador.listarTareasCount();
            
            //Obtenemos el modelo de la tabla
            DefaultTableModel modeloCount = (DefaultTableModel) tblTareasCount.getModel();
            
            //Limpiar el modelo
            modeloCount.setRowCount(0);
            
            //Vamos a agregar las filas con los datos de las tareas
            for(TareaCount tareaCount : tareasCount){
                Object[] fila = {
                    tareaCount.getCantidadTareas(),
                    tareaCount.getCantidadTareasActivas(),
                    tareaCount.getCantidadTareasInactivas()
                };
                modeloCount.addRow(fila);
            }
            
        }catch(Exception ex){
            System.out.println("Error al cargas tareas" + ex.getMessage());
            ex.printStackTrace();
        }
    }
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TareasVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TareasVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TareasVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TareasVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TareasVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarTarea;
    private javax.swing.JButton btnCambiarEstadoTarea;
    private javax.swing.JButton btnCargarTareas;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JPanel pnlIngresoDatos;
    private javax.swing.JTable tblTareas;
    private javax.swing.JTable tblTareasCount;
    private javax.swing.JTextArea txaDescripcion;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
